import { execFile } from 'child_process';
import { promisify } from 'util';
import { promises as fs } from 'fs';
import * as os from 'os';
import * as path from 'path';

const execFileAsync = promisify(execFile);

/** Path to the yt-dlp binary. Overridable for environments that install it elsewhere. */
const YTDLP_BIN = process.env.YTDLP_PATH || 'yt-dlp';

export interface YouTubeTranscript {
  videoId: string;
  title?: string;
  channel?: string;
  durationString?: string;
  /** Language code of the captions actually returned (e.g. "en", "pt"). */
  language?: string;
  /** True when the captions are machine-generated (auto-captions) rather than human-authored. */
  autoGenerated: boolean;
  /** Cleaned plain-text transcript. */
  text: string;
}

export class YouTubeTranscriptError extends Error {}

/**
 * Extract the 11-character video id from any common YouTube URL form, or accept
 * a bare id. Returns null when nothing usable is found.
 */
export function extractYouTubeId(input: string): string | null {
  const raw = input.trim();
  // Bare id.
  if (/^[A-Za-z0-9_-]{11}$/.test(raw)) return raw;

  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }

  const host = url.hostname.replace(/^www\./, '').toLowerCase();
  if (host === 'youtu.be') {
    const id = url.pathname.split('/').filter(Boolean)[0];
    return id && /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
  }
  if (host === 'youtube.com' || host === 'm.youtube.com' || host === 'youtube-nocookie.com') {
    const v = url.searchParams.get('v');
    if (v && /^[A-Za-z0-9_-]{11}$/.test(v)) return v;
    // /embed/ID, /shorts/ID, /live/ID, /v/ID
    const parts = url.pathname.split('/').filter(Boolean);
    if (parts.length >= 2 && ['embed', 'shorts', 'live', 'v'].includes(parts[0])) {
      const id = parts[1];
      if (/^[A-Za-z0-9_-]{11}$/.test(id)) return id;
    }
  }
  return null;
}

/**
 * Convert a WebVTT subtitle document into clean plain text: drops the header,
 * cue indices, timestamp/cue-setting lines and inline timing tags, decodes the
 * handful of HTML entities YouTube emits, and removes duplicate lines (YouTube
 * auto-captions repeat a rolling window, so the same line recurs across cues).
 */
function vttToText(vtt: string): string {
  const lines = vtt.split(/\r?\n/);
  const out: string[] = [];
  const seen = new Set<string>();
  for (const rawLine of lines) {
    let line = rawLine.trim();
    if (!line) continue;
    if (line === 'WEBVTT') continue;
    if (/^(Kind|Language|NOTE|STYLE|Region):/i.test(line)) continue;
    if (line.includes('-->')) continue; // timestamp + cue settings
    if (/^\d+$/.test(line)) continue; // numeric cue index
    line = line.replace(/<[^>]+>/g, '').trim(); // inline <00:00:00.000>/<c> tags
    if (!line) continue;
    line = line
      .replace(/&nbsp;/g, ' ')
      .replace(/&#39;/g, "'")
      .replace(/&quot;/g, '"')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&amp;/g, '&')
      .trim();
    if (!line || seen.has(line)) continue;
    seen.add(line);
    out.push(line);
  }
  return out.join('\n');
}

interface InfoJson {
  id?: string;
  title?: string;
  channel?: string;
  uploader?: string;
  duration_string?: string;
  /** Human-authored subtitle tracks, keyed by language code. */
  subtitles?: Record<string, unknown>;
  /** Machine-generated caption tracks, keyed by language code. */
  automatic_captions?: Record<string, unknown>;
}

interface ChosenTrack {
  lang: string;
  autoGenerated: boolean;
}

/**
 * Choose a single caption track to download from the available manual and
 * auto-caption language maps. Human-authored subtitles win over auto-captions;
 * within each, the requested language wins over English, an exact code wins
 * over a regional/translation variant, and a non-hyphenated "original" track
 * wins over auto-translations (which YouTube names like "pt-en" = "Portuguese
 * from English"). Returns null when neither map has anything.
 */
function chooseTrack(
  manual: Record<string, unknown>,
  auto: Record<string, unknown>,
  preferredLang?: string
): ChosenTrack | null {
  const maps: Array<[boolean, string[]]> = [
    [false, Object.keys(manual)],
    [true, Object.keys(auto)],
  ];
  const wanted = preferredLang ? [preferredLang.toLowerCase(), 'en'] : ['en'];

  // 1. Exact language match, manual tracks before auto, requested lang first.
  for (const w of wanted) {
    for (const [isAuto, keys] of maps) {
      const hit = keys.find((k) => k.toLowerCase() === w);
      if (hit) return { lang: hit, autoGenerated: isAuto };
    }
  }
  // 2. Regional variant of a wanted language, e.g. "en-US", "pt-BR".
  for (const w of wanted) {
    for (const [isAuto, keys] of maps) {
      const hit = keys.find((k) => k.toLowerCase().startsWith(`${w}-`));
      if (hit) return { lang: hit, autoGenerated: isAuto };
    }
  }
  // 3. Last resort: any track, preferring a non-translation (no-hyphen) code.
  for (const [isAuto, keys] of maps) {
    const original = keys.find((k) => !k.includes('-')) || keys[0];
    if (original) return { lang: original, autoGenerated: isAuto };
  }
  return null;
}

export class YouTubeTranscriptClient {
  private async runYtDlp(args: string[]): Promise<{ stdout: string; stderr: string; failed: boolean }> {
    try {
      const { stdout, stderr } = await execFileAsync(YTDLP_BIN, args, {
        timeout: 60_000,
        maxBuffer: 64 * 1024 * 1024,
      });
      return { stdout, stderr, failed: false };
    } catch (error: any) {
      return {
        stdout: String(error?.stdout || ''),
        stderr: String(error?.stderr || error?.message || ''),
        failed: true,
      };
    }
  }

  /**
   * Fetch and clean the captions for a YouTube video.
   *
   * Runs in two passes to stay polite to YouTube (a single greedy download of
   * every matching track triggers HTTP 429): first dumps the video metadata
   * JSON to learn which caption tracks exist, then downloads exactly one chosen
   * track. Prefers human-authored subtitles in the requested language (then
   * English), falling back to auto-captions. Throws YouTubeTranscriptError with
   * a user-facing message on failure.
   */
  async fetch(urlOrId: string, options: { lang?: string } = {}): Promise<YouTubeTranscript> {
    const videoId = extractYouTubeId(urlOrId);
    if (!videoId) {
      throw new YouTubeTranscriptError(
        'Not a valid YouTube URL or video id. Pass a watch/youtu.be/shorts URL or an 11-character id.'
      );
    }

    const lang = options.lang?.trim() || undefined;
    const url = `https://www.youtube.com/watch?v=${videoId}`;

    // Pass 1: metadata + available-track maps, no subtitle download (-J dumps
    // the full info JSON to stdout).
    const meta = await this.runYtDlp(['-J', '--skip-download', '--no-playlist', '--no-warnings', url]);
    if (!meta.stdout.trim()) {
      const detail = meta.stderr.split('\n').filter(Boolean).pop() || 'unknown error';
      throw new YouTubeTranscriptError(`yt-dlp could not read this video: ${detail}`);
    }
    let info: InfoJson | null;
    try {
      info = JSON.parse(meta.stdout) as InfoJson | null;
    } catch {
      throw new YouTubeTranscriptError('yt-dlp returned an unreadable response for this video.');
    }
    if (!info || typeof info !== 'object') {
      // Unavailable/private/deleted videos make yt-dlp print "null" with the
      // real reason on stderr.
      const detail = meta.stderr.split('\n').filter(Boolean).pop() || 'video unavailable';
      throw new YouTubeTranscriptError(`yt-dlp could not read this video: ${detail}`);
    }

    const chosen = chooseTrack(info.subtitles || {}, info.automatic_captions || {}, lang);
    if (!chosen) {
      throw new YouTubeTranscriptError(
        'No captions or subtitles are available for this video (no manual or auto-generated track found).'
      );
    }

    // Pass 2: download just the chosen track.
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ytsub-'));
    try {
      const dl = await this.runYtDlp([
        '--skip-download',
        '--no-playlist',
        '--no-warnings',
        chosen.autoGenerated ? '--write-auto-subs' : '--write-subs',
        '--sub-langs', chosen.lang,
        '--sub-format', 'vtt',
        '-o', path.join(tmpDir, '%(id)s.%(ext)s'),
        url,
      ]);

      const entries = await fs.readdir(tmpDir);
      const vttFile = entries.find((f) => f.endsWith('.vtt'));
      if (!vttFile) {
        const detail = dl.stderr.split('\n').filter(Boolean).pop() || 'no subtitle file produced';
        throw new YouTubeTranscriptError(`Could not download the captions track: ${detail}`);
      }

      const text = vttToText(await fs.readFile(path.join(tmpDir, vttFile), 'utf-8'));
      if (!text.trim()) {
        throw new YouTubeTranscriptError('The captions track was empty after parsing.');
      }

      return {
        videoId,
        title: info.title,
        channel: info.channel || info.uploader,
        durationString: info.duration_string,
        language: chosen.lang,
        autoGenerated: chosen.autoGenerated,
        text,
      };
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
    }
  }
}
