// Sandbox + Remote file browser data
const sandboxTree = {
  root: '~/projects/logistics-app',
  host: 'sandbox · node-20',
  status: 'live',
  nodes: [
    { name: 'scripts', type: 'dir', open: true, children: [
      { name: 'dev.sh',          type: 'sh',   change: 'M', size: '2.1K' },
      { name: 'setup.sh',        type: 'sh',                size: '0.9K' },
      { name: 'seed.ts',         type: 'ts',                size: '4.4K' },
    ]},
    { name: 'backend', type: 'dir', open: true, children: [
      { name: 'src', type: 'dir', open: true, children: [
        { name: 'index.js',      type: 'js',                size: '1.2K' },
        { name: 'auth.js',       type: 'js',   change: 'M', size: '3.8K' },
        { name: 'routes.js',     type: 'js',                size: '5.1K' },
      ]},
      { name: '.env.local',      type: 'env',  change: 'A', size: '180 B' },
      { name: 'package.json',    type: 'json',              size: '1.4K' },
    ]},
    { name: 'admin-dashboard', type: 'dir', children: [] },
    { name: 'driver-app',      type: 'dir', children: [] },
    { name: 'customer-app',    type: 'dir', children: [] },
    { name: 'README.md',       type: 'md', size: '3.2K' },
    { name: 'package.json',    type: 'json', size: '0.8K' },
  ],
};

const remoteTree = {
  root: '/var/www/logistics',
  host: 'deploy@logistics-prod.acme.io',
  status: 'connected · 18ms',
  nodes: [
    { name: 'dist', type: 'dir', children: [
      { name: 'index.html',      type: 'html', size: '12K',  readonly: true },
      { name: 'assets',          type: 'dir',                readonly: true, children: [] },
    ]},
    { name: 'logs', type: 'dir', open: true, children: [
      { name: 'app-2026-05-08.log',   type: 'log', size: '4.2M', readonly: true, hot: true },
      { name: 'app-2026-05-07.log',   type: 'log', size: '8.1M', readonly: true },
      { name: 'error.log',            type: 'log', size: '128K', readonly: true, hot: true, change: '!' },
    ]},
    { name: '.env.production',  type: 'env',  size: '420 B', readonly: true, locked: true },
    { name: 'nginx.conf',       type: 'conf', size: '2.0K', readonly: true },
    { name: 'pm2.config.js',    type: 'js',   size: '0.6K', readonly: true },
  ],
};

// Sample file content for the preview
const sampleFiles = {
  'dev.sh': {
    lang: 'bash',
    lines: [
      ['#!/usr/bin/env bash', 'c'],
      ['set -euo pipefail', 'k'],
      ['', ''],
      ['# Generate a secure JWT_SECRET on first run.', 'c'],
      ['if [ ! -f backend/.env.local ]; then', 'k'],
      ['  echo "JWT_SECRET=$(openssl rand -hex 32)" > backend/.env.local', 't'],
      ['  echo "✓ created backend/.env.local"', 't'],
      ['fi', 'k'],
      ['', ''],
      ['export $(cat backend/.env.local | xargs)', 't'],
      ['', ''],
      ['echo "Starting Backend (port 3000)…"', 't'],
      ['(cd backend && npm run dev) &', 't'],
      ['BACKEND_PID=$!', 't'],
    ],
  },
  '.env.local': {
    lang: 'env',
    lines: [
      ['# Auto-generated by scripts/dev.sh — do not commit', 'c'],
      ['JWT_SECRET=8a3f…d2c7e1b9   # 32-byte random hex', 't'],
      ['SESSION_SECRET=4b1e…9f2a8d', 't'],
      ['DATABASE_URL=postgres://localhost:5432/logistics_dev', 't'],
      ['REDIS_URL=redis://localhost:6379', 't'],
    ],
  },
  'error.log': {
    lang: 'log',
    lines: [
      ['[2026-05-08 13:58:21] ERR  upstream timeout on /api/dispatch (4ms)', 'e'],
      ['[2026-05-08 13:58:22] ERR  upstream timeout on /api/dispatch (3ms)', 'e'],
      ['[2026-05-08 13:58:24] WARN slow query 412ms — orders.recent', 'w'],
      ['[2026-05-08 13:58:30] INFO restarted worker pid=2841', 't'],
      ['[2026-05-08 13:59:02] ERR  upstream timeout on /api/dispatch (5ms)', 'e'],
    ],
  },
  '_default': {
    lang: 'text',
    lines: [
      ['// File contents will appear here.', 'c'],
      ['// Click a file in the tree to preview it inline.', 'c'],
    ],
  },
};

window.AppData.files = { sandbox: sandboxTree, remote: remoteTree, samples: sampleFiles };
